name: Deploy Staging Infrastructure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure/staging

    env:
      TF_VAR_ami_id: ${{ secrets.TF_VAR_AMI_ID }}
      TF_VAR_aws_region: ${{ secrets.TF_VAR_AWS_REGION }}
      TF_VAR_instance_type: ${{ secrets.TF_VAR_INSTANCE_TYPE }}
      TF_VAR_key_name: ${{ secrets.TF_VAR_KEY_NAME }}
      TF_VAR_security_group_name: ${{ secrets.TF_VAR_SECURITY_GROUP_NAME }}
      TF_VAR_subnet_id: ${{ secrets.TF_VAR_SUBNET_ID }}
      TF_VAR_vpc_id: ${{ secrets.TF_VAR_VPC_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC And this workflow directly connects to AWS via GitHub OIDC and runs Terraform to create or update the cloud resources.
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.TF_VAR_AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.2

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply (on push to develop)
        if: github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
